version: "2"
services:
  web:
    build: .
    command: npm run start
    environment:
      PIN: mhgeyfgnxwurfgnc
      SECRET_KEY: hmkhaDHADXHNADMHSDIJDKBjhgxjhd
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules/
      - /usr/data/
    ports:
      - "3000:3000"
